### PR TITLE
Span Tag Added

### PR DESCRIPTION
**Pull request by Shookrun**

### CODE REVIEW

**Comment by Shookrun** [comment]
add new tag

**Review by ElcinQuliyev — COMMENTED** [review]
Deisdirildi

**Comment by Shookrun** [comment]
Span Add

**Comment by ElcinQuliyev** [comment]
Deisdi

**Comment by Shookrun** [comment]
Span Added

**Comment by Shookrun** [comment]
Span Added

**Comment by Shookrun** [comment]
Span Tag

**Pull request merged**
